use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::compiler;
use crate::span::Source;

pub const RUNTIME_C: &str = include_str!("../runtime/slim_rt.c");
pub const RUNTIME_H: &str = include_str!("../runtime/slim_rt.h");

#[derive(Clone, Debug)]
pub struct BootstrapReport {
    pub build_dir: PathBuf,
    pub compiler: PathBuf,
    pub fixed_c_bytes: usize,
}

pub fn bootstrap(root: &Path) -> Result<BootstrapReport, String> {
    let source_path = root.join("selfhost/slimc.slim");
    let source_text = fs::read_to_string(&source_path)
        .map_err(|error| format!("cannot read {}: {error}", source_path.display()))?;
    let source = Source::new(&source_path, source_text);
    let compilation = compiler::compile(source.clone());
    if !compilation.succeeded() {
        let diagnostics = compilation
            .diagnostics
            .iter()
            .map(|diagnostic| diagnostic.render_human(&source))
            .collect::<String>();
        return Err(format!(
            "stage 0 rejected the self-hosted compiler\n{diagnostics}"
        ));
    }
    let stage0_c = compilation
        .emit_c()
        .ok_or_else(|| "stage 0 did not emit C".to_owned())?;

    let build = root.join("build/selfhost");
    fs::create_dir_all(&build)
        .map_err(|error| format!("cannot create {}: {error}", build.display()))?;
    write(&build.join("slim_rt.c"), RUNTIME_C.as_bytes())?;
    write(&build.join("slim_rt.h"), RUNTIME_H.as_bytes())?;

    let stage0_c_path = build.join("stage0.c");
    let stage1 = build.join("stage1");
    write(&stage0_c_path, stage0_c.as_bytes())?;
    compile_native(&build, &stage0_c_path, &stage1)?;

    let stage2_c_path = build.join("stage2.c");
    let stage2_c = run_compiler(&stage1, &source_path)?;
    write(&stage2_c_path, &stage2_c)?;

    let stage2 = build.join("stage2");
    compile_native(&build, &stage2_c_path, &stage2)?;

    let stage3_c_path = build.join("stage3.c");
    let stage3_c = run_compiler(&stage2, &source_path)?;
    write(&stage3_c_path, &stage3_c)?;

    if stage2_c != stage3_c {
        let first = stage2_c
            .iter()
            .zip(&stage3_c)
            .position(|(left, right)| left != right)
            .unwrap_or_else(|| stage2_c.len().min(stage3_c.len()));
        return Err(format!(
            "bootstrap fixed point failed at byte {first} (stage 2: {} bytes, stage 3: {} bytes)",
            stage2_c.len(),
            stage3_c.len()
        ));
    }

    let smoke_source = root.join("examples/hello.slim");
    let smoke_c_path = build.join("hello.c");
    let smoke_c = run_compiler(&stage2, &smoke_source)?;
    write(&smoke_c_path, &smoke_c)?;
    let smoke = build.join("hello");
    compile_native(&build, &smoke_c_path, &smoke)?;
    let output = Command::new(&smoke)
        .output()
        .map_err(|error| format!("cannot run {}: {error}", smoke.display()))?;
    if !output.status.success() || output.stdout != b"hello from SLIM\n" {
        return Err(format!(
            "self-hosted smoke test failed: status {}, stdout {:?}, stderr {:?}",
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    Ok(BootstrapReport {
        build_dir: build,
        compiler: stage2,
        fixed_c_bytes: stage2_c.len(),
    })
}

pub fn workspace_root() -> Result<PathBuf, String> {
    env::current_dir().map_err(|error| format!("cannot find workspace: {error}"))
}

pub fn run_compiler(compiler: &Path, source: &Path) -> Result<Vec<u8>, String> {
    let output = Command::new(compiler)
        .arg(source)
        .output()
        .map_err(|error| format!("cannot run {}: {error}", compiler.display()))?;
    if !output.status.success() {
        let tail_start = output.stdout.len().saturating_sub(1_000);
        return Err(format!(
            "{} failed with {}\n{}\nlast generated bytes:\n{}",
            compiler.display(),
            output.status,
            String::from_utf8_lossy(&output.stderr),
            String::from_utf8_lossy(&output.stdout[tail_start..])
        ));
    }
    if !output.stderr.is_empty() {
        return Err(format!(
            "{} wrote unexpected diagnostics:\n{}",
            compiler.display(),
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    Ok(output.stdout)
}

pub fn compile_native(include: &Path, source: &Path, output: &Path) -> Result<(), String> {
    let compiler = env::var_os("CC").unwrap_or_else(|| "clang".into());
    let result = Command::new(&compiler)
        .arg("-std=c11")
        .arg("-O3")
        .arg("-flto")
        .arg("-Wall")
        .arg("-Wextra")
        .arg("-Werror")
        .arg("-I")
        .arg(include)
        .arg(source)
        .arg(include.join("slim_rt.c"))
        .arg("-o")
        .arg(output)
        .output()
        .map_err(|error| format!("cannot execute {:?}: {error}", compiler))?;
    if !result.status.success() {
        return Err(format!(
            "native build of {} failed with {}\n{}{}",
            source.display(),
            result.status,
            String::from_utf8_lossy(&result.stdout),
            String::from_utf8_lossy(&result.stderr)
        ));
    }
    Ok(())
}

fn write(path: &Path, bytes: &[u8]) -> Result<(), String> {
    fs::write(path, bytes).map_err(|error| format!("cannot write {}: {error}", path.display()))
}
